---
name: Upload
description: Compiles and uploads LaTeX documents

inputs:
  aws-access-key-id:
    description: AWS Access Key ID
    required: true
  aws-secret-access-key:
    description: AWS Secret Access Key
    required: true
  aws-s3-endpoint:
    description: AWS S3 Endpoint
    required: true

runs:
  using: composite

  steps:
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@e2f99d4b3685b0da93f97e1b86ad8fab81105098 # v3
      with:
        root_file: ./out/merge/*.tex
        working_directory: ./
        args: -output-directory=./out/pdf/
        latexmk_use_xelatex: true

    - name: Compress Artifact(s)
      shell: bash
      run: |-
        cd ./out/pdf/
        tar cf Artifact.tar.gz -- *.pdf

    - name: Upload to Private Artifact Repository
      shell: bash
      run: |-
        aws --endpoint-url ${{ inputs.aws-s3-endpoint }} s3 sync ./out/pdf/ s3://workflow-artifacts/texcv --exclude="*" --include="Artifact.tar.gz"
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        AWS_DEFAULT_REGION: "us-east-1"
